apiVersion: v1
kind: Pod
metadata:
  name: test-controller
  labels:
    app: test-controller
spec:
  containers:
    - name: test-runner
      image: gorkemc/webtest_insider:latest
      env:
        - name: SELENIUM_SERVER_URL
          value: "http://chrome-node:4444/wd/hub"
      command: ["sh", "-c", "pytest --base-url=$SELENIUM_SERVER_URL -vvl"]
      resources:
        limits:
          memory: "1Gi"
          cpu: "0.5"